# Generated by Django 5.0.6 on 2024-06-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=25)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userPassword', models.CharField(max_length=10)),
            ],
        ),
    ]
