# Generated by Django 5.0.6 on 2024-06-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='userId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
